version: '3.9'

#
# Environment vars for orderjutsu download link and database login credentials
# are loaded from the ".env" file.
#
# So make sure all required environment variables are present in that file:
#    ORDERJUTSU_LINK=https://orderjutsu.org/?download_file=...
#    ORDERJUTSU_VERSION=1.xx.xx
#    DB_DATABASE=orderjutsu
#    DB_USER=orderjutsu
#    DB_PASSWORD=yourPassword123
# 

services:

  # php container is based on the php:7.1-fpm-alpine image extended by additional
  # packages, php modules and composer required by orderjutsu to run properly.
  php:
    build:
      context: php
      dockerfile: Dockerfile
    image: php/orderjutsu:7.1-fpm-alpine
    container_name: orderjutsu-php
    restart: unless-stopped
    env_file: .env
    environment:
        - DB_HOST=orderjutsu-db
    volumes:
      - orderjutsu-files:/srv
      - ./php/fpm-www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/setup.sh:/docker-entrypoint-setup.sh
    networks:
      - orderjutsu-network
    depends_on:
      - db
  
  # nginx service just provides the webserver. 
  # Gets access to the orderjutsu files via shared volume to serve static
  # files (images, ...)    
  nginx:
    image: nginxinc/nginx-unprivileged:alpine-slim
    container_name: orderjutsu-nginx
    restart: unless-stopped
    volumes:
      - orderjutsu-files:/srv:nocopy
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
    networks:
      - orderjutsu-network
    ports:
      - "8080:8080"
    depends_on:
      - php
      
  db:
    image: mariadb:latest
    container_name: orderjutsu-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - orderjutsu-dbdata:/var/lib/mysql
    networks:
      - orderjutsu-network

networks:
    orderjutsu-network:
      driver: bridge
    
volumes:
    orderjutsu-files:
      name: orderjutsu-${ORDERJUTSU_VERSION}
      driver: local
    orderjutsu-dbdata:
      driver: local     